### ISSUE TITLE
Selection Highlight Not Working

### ISSUE THREAD

**Issue by Reaomaol** [jyaoma/vscode-lsl#8]
When you double-click to highlight a function, event or variable, normally the scroll bar highlights all instances of the highlighted selection.  Unfortunately this functionality is broken once LSL Language Server extension is installed, even if another extension is installed for that specific purpose.

**Comment by jyaoma** [comment]
Hey @Reaomaol very sorry for the late reply.

I can't seem to reproduce. I've attached screenshots below of my testing. If you are still seeing the issue, please open another issue with a link to a [pastebin](https://pastebin.com/) with your code. I'm going to close this issue for now. Thanks!

Function:
![image](https://github.com/user-attachments/assets/ec695bd8-c4a2-4978-895a-972693e7c898)

Event:
![image](https://github.com/user-attachments/assets/69e8e44f-c8cd-4932-b0db-2cdee66c7bfe)

Variable:
![image](https://github.com/user-attachments/assets/72700c88-a5f5-4bb7-89c5-d8fc6ae3c413)
